var dialog = [
    "Hi there!",
    "How's your day so far?",
    "YIPPEE!!",
    "Check out the other projects in the NunnerVerse!",
    "Jot down notes below :>",
    "Use this as a to-do list!",
    "What should we write today?",
    "I'm Sketchy, your note-taking pal :3",
    ":D",
    "Don't forget to take breaks every now and then!",
    "It's --:-- right now.",
    "Always stay positive!",
    "Your notes auto-save, so don't worry.",
    "I believe in you!",
    "Relax; Everything will be okay!",
    "Your notes are private, only visible to you!",
    "Your secrets are safe with me ;)",
    "Use multiple notes for organization!",
    "Stay on task!!",
    "Maintain focus; You got this!",
    "Make sure to touch grass…I'm watching you…",
    "Have a great day~",
    "Why not stand up and stretch!",
    "Stay hydrated!!",
    "Enjoy your week!",
    "You only live once~",
    "Keep pushing—You're almost there!",
    "Just believe!",
    "Don't let others determine who you are!",
    "YOU ARE CAPABLE OF GREAT THINGS",
    "Do your best!",

    /* HOLIDAYS */
    /*"Merry Christmas!",
    "Happy holidays!",
    "guys santa claus is coming to town",
    "'Tis the season to be jolly~",*/
];