var dialog = [
    "Hi there!",
    "How's your day so far?",
    "YIPPEE!!",
    "Check out the other projects in the NunnerVerse!",
    "Jot down notes below :>",
    "Use this as a to-do list!",
    "What should we write today?",
    "I'm Sketchy, your note-taking pal :3",
    ":D",
    "Don't forget to take breaks every now and then!",
    "It's --:-- right now.",
    "Always stay positive!",
    "Your notes auto-save, so don't worry.",
    "I believe in you!",
    "Relax; Everything will be okay!",
    "Your notes are private, only visible to you!",
    "Your secrets are safe with me ;)",
    "Use multiple notes for organization!",
    "Stay on task!!",
    "Maintain focus; You got this!",
];